export const DEFAULT_JARVIS_CHAT_NAME = "Jarvis";

export const AUDIT_EVENTS = {
  WHATSAPP_QR_GENERATED: "WHATSAPP_QR_GENERATED",
  WHATSAPP_CONNECTED: "WHATSAPP_CONNECTED",
  WHATSAPP_DISCONNECTED: "WHATSAPP_DISCONNECTED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  PERMISSION_CHECK: "PERMISSION_CHECK",
  AI_INTENT_PARSED: "AI_INTENT_PARSED",
  REMINDER_CREATED: "REMINDER_CREATED",
  REMINDER_EXECUTED: "REMINDER_EXECUTED",
  REMINDER_FAILED: "REMINDER_FAILED",
  MEMORY_STORED: "MEMORY_STORED",
  VAULT_ENTRY_SAVED: "VAULT_ENTRY_SAVED",
  VAULT_ENTRY_ACCESSED: "VAULT_ENTRY_ACCESSED",
  SYSTEM_ERROR: "SYSTEM_ERROR"
};
